name: Make HTML
on:
  workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: goto directory
          uses: cd _builder
        - name: install dependencies
          run: npm install
        - name: generate html
          run: node ./_builder/index.js
        - name: goto directory
          uses: cd ..
        #- name: Setup Pages
        #  uses: actions/configure-pages@v5
        #- name: Build with Jekyll
        #  uses: actions/jekyll-build-pages@v1
        #  with:
        #    source: ./
        #    destination: ./_site
        #- name: Upload artifact
        #  uses: actions/upload-pages-artifact@v3

    # Deployment job
    #deploy:
    #  environment:
    #    name: github-pages
    #    url: ${{ steps.deployment.outputs.page_url }}
    #  runs-on: ubuntu-latest
    #  needs: build
    #  steps:
    #    - name: Deploy to GitHub Pages
    #      id: deployment
    #      uses: actions/deploy-pages@v4